services:
  - type: web
    name: minicompiler
    env: node
    buildCommand: apt-get update && apt-get install -y g++ && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18